src/App.vue
=> chore: CI/CD Workflow 테스트

src/components/HelloWorld.vue
=> hotfix: remove msg props

.env.development, src/api/index.ts, src/api/login.ts, src/components/BaseInput.vue, src/components/HelloWorld.vue, src/components/LoginModal.vue, src/types/login.types.ts
- 로그인 기능 완성
- 개발 환경 변수를 헤로쿠 서버 주소로 변경하였습니다. 아래와 같이 변경해서 사용하시면 될 것 같습니다. (는 이미 커밋으로 관리되고 있군요?)
```bash
// .env.development
VUE_APP_BASE_URL=https://pickabook-server-develop.herokuapp.com
```
- 타입 정의를 위해 types 폴더 안에 login.types.ts 파일을 생성하였는데, users로 하나로 묶는 게 나을까요? 의견주시면 바로 반영하겠습니다.
- axios를 apiGet, apiPost, apiPut, apiDelete 이렇게 총 4가지 래퍼 함수를 만들어서 구성하였습니다. index에서 설정한 값을 다른데서 쓰려다보니 이 방법 말고는 안 떠오르네요. 더 좋은 아이디어 있으시면 공유 부탁드립니다. 바로 반영 가능!
```javascript
const apiGet = (
url: string,
options?: AxiosRequestConfig
): Promise<AxiosResponse> => {
return axiosInstance.get(url, options);
};
const apiPost = <RequestBody>(
url: string,
body?: RequestBody,
options?: AxiosRequestConfig
): Promise<AxiosResponse> => {
return axiosInstance.post(url, body, options);
};
const apiPut = <RequestBody>(
url: string, …
```
=> feat: login logic

src/api/login.ts
=> feat: 회원가입 빠진 로직 추가

.env.production
- 프로덕션 환경변수 수정
- 프로덕션에 환경변수 설정이 안되어있어서 
헤로쿠 스테이징 서버로 설정해두었습니다.
추후 AWS나 별도의 프로덕션 API 서버가 배포되면 그쪽으로 돌려야합니다.
=> Modify .env.production

.github/workflows/deploy-to-netlify.yml, .github/workflows/test-feature.yml
=> chore: github actions 수정 - pass with no tests

src/components/LoginModal.vue, src/components/SignupModal.vue
- 로그인/회원가입 사소한 UX 개선
- `required` 속성을 통한 1차 유효성 검사
- 응답 지연 시 재요청 방지
=> feat: 로그인/회원가입 사소한 UX 개선

src/components/AuthModalLogin.vue, src/components/AuthModalSignup.vue
- 에러 alert를 중복해서 띄우는 멍청한 실수를 바로잡았습니다.
-
=> chore: 중복된 API 에러 메시지 alert 제거

src/api/extension.ts, src/components/AuthModalLogin.vue, src/components/TheGnb.vue
=> chore: Cannot find name 'chrome' ts-ignore 처리

src/api/index.ts
- axios 인터셉터에서 config 설정하는 코드 수정해두었습니다!
기존 방식으로는 헤더에 담기질 않네요 ㅠㅠ
-
=> hotfix: 헤더에 토큰 싣는 코드 수정

src/api/auth.api.ts, src/components/AuthModalLogin.vue, src/components/AuthModalSignup.vue, src/components/BaseButton.vue, src/components/BaseInput.vue, src/components/Snackbar.vue, src/components/TheGnb.vue, src/store/auth.store.ts, src/types/auth.types.ts, src/views/ExploreView.vue, yarn.lock
- 이메일 중복 확인 API 추가
[완료]
- 이메일 중복 확인 API 추가
- 인증코드 발송 전, 이메일 중복 여부를 먼저 확인합니다.
- Snackbar 메시지 적용
- 로그인, 회원가입 모달 대부분의 Alert를 Snackbar를 대체했습니다. (감사합니다 👍🏻)
- BaseButton, BaseInput 사소한 디자인 수정
[예정]
- 유저 아이콘 클릭 시 ContextMenu가 한 번에 디스플레이 되지 않는 현상 수정 중
- Snackbar Messages 모듈화
=> GNB - 이메일 중복 확인 API 추가

src/assets/icons/check-white.svg, src/components/AuthModalSignup.vue, src/types/auth.types.ts
- 회원가입 이용약관 필드 추가
**완료**
- 회원가입 이용약관 필드 추가
- 사소한 UX 추가 (ex- `isSending` -> `spinner` 처리)
**예정**
- Checkbox 컴포넌트 분리
=> 회원가입 이용약관 필드 추가

src/App.vue, src/components/BaseContextMenu.vue, src/components/TheGnb.vue, src/composables/index.ts, src/composables/useOnClickOutside.ts, src/composables/useOnScroll.ts, src/views/LandingPageView.vue
완료
- 랜딩 페이지 기본 레이아웃 추가하였습니다.
- GNB 컨텍스트 메뉴 ON/OFF 시 마우스 클릭이 무시되는 버그를 수정하였습니다.
- DOM 조작하는 composable의 경우 unmounted 시 이벤트 제거되게끔 처리하였습니다.
예정
- GNB fixed 처리
=> feat: 랜딩 페이지 기본 레이아웃

src/components/BookmarkList.vue, src/components/BookmarkListItem.vue
=> fix: context menu 로직 수정

src/App.vue
=> style: router-view wrapper flex 스타일 제거

src/components/TheGnb.vue
=> style: border-bottom 스타일 부여 엘리먼트 변경

src/components/BaseContextMenu.vue, src/components/BaseContextMenuItem.vue, src/components/TheGnb.vue
유저 컨텍스트 메뉴
- 유저 아이콘 눌렀을 때 토글이 작동하지 않는 버그 수정 (onClickOutside 로직 수정)
- 마크업 구조 변경
=> fix: 유저 컨텍스트 메뉴 버그 수정 및 간단한 리팩터링

src/components/TheGnb.vue
=> feat: 북마크 알림 클릭 시 새로운 탭으로 URL 열기

src/components/BookmarkList.vue
=> style: 북마트 필터 컨텍스트 메뉴 스타일 수정

src/components/BookmarkList.vue
=> 스낵바 관련 타입 에러 수정

src/components/BookmarkList.vue, src/composables/useTag.ts, src/store/bookmark.store.ts
=> feat: 로더 추가

src/store/bookmark.store.ts
=> fix: 최초 북마크 생성 시 전체 태그가 없어서 생기는 버그

src/store/bookmark.store.ts
=> fix: 태그를 삭제했을 때 전체 목록에는 남아있는 버그 수정

src/components/AuthModalLogin.vue, src/components/TheGnb.vue
- 웹앱에서 로그아웃했을 때 익스텐션도 로그아웃하도록 수정하였습니다!
-
=> feat: 로그아웃시 익스텐션도 같이 로그아웃시키는 로직 추가

src/components/TheGnb.vue
=> hotfix: JSON.parse 에러 수정

src/components/BookmarkList.vue, src/components/BookmarkModal.vue, src/composables/useTag.ts, src/store/bookmark.store.ts
=> fix: 북마크 추가시 현재 화면의 태그에 해당하지 않음에도 리스트에 추가되는 버그 수정

package.json
=> hotfix: 테스트 스크립트 임시로 제거

src/App.vue, src/api/index.ts, src/api/noti.api.ts, src/components/AuthModalLogin.vue, src/components/AuthModalSignup.vue, src/components/BaseModal.vue, src/components/TheGnb.vue, src/components/TheSnb.vue, src/composables/useNotification.ts, src/router/index.ts, src/store/notification.store.ts, src/types/index.ts
- Auth 관련 모듈(GNB 관련 컴포넌트, router 네비게이션 가드 등) 리팩터링 및 기능 개선
**(익스텐션 새 버전 배포 후 테스트를 위한 중간 Merge)**
- <script setup> syntax로 변경
- Notification 컴포저블 생성
- 로그인 관련 로직 개선
- `AUTH_INVALID_TOKEN` 에러코드 응답 시 로그아웃 및 메인 페이지로 리다이렉트
- 로그인한 상태로 '로그인' 버튼 클릭 시 즉시 메인 페이지로 이동
-  Vue 2 Options API 문법 삭제(TheGnB, Signup, Login 모달)
Close #75
=> Auth 관련 모듈 리팩터링 및 기능 개선

src/components/AuthModalLogin.vue, src/components/TheGnb.vue, src/composables/useAuth.ts, src/router/index.ts, src/views/LandingPageView.vue
=> fix: 로그인 상태로 루트 경로 접근 시 익스텐션 메시지 전송 되지 않는 현상 해결

src/components/TheGnb.vue
=> fix: GNB 컴포넌트 마운트 시 노티 리스트 페칭하도록 변경

src/views/LandingPageView.vue
=> fix: 랜딩페이지 로그인 여부 판단 기준을 Global State에서 Local Storage 값으로 변경

src/router/index.ts
=> fix: 루트 경로 접근 시 크롬 캐시 스토리지 제거
